name: R-CMD-check
on: [push, pull_request]
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install renv
        run: R -q -e 'install.packages("renv"); if (file.exists("renv.lock")) renv::restore()'
